const data = {
  products: [
    {
      _id: "1",
      name: "Denim Jacket",
      category: "Jacket",
      image: "/images/product-2.jpg",
      price: 150,
      brand: "Denim",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Black T-Shirt",
      category: "T-Shirt",
      image: "/images/product-3.jpg",
      price: 100,
      brand: "Adiddas",
      rating: 4.3,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Printed Shirt",
      category: "Shirt",
      image: "/images/product-4.jpg",
      price: 130,
      brand: "HRX",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Polo T-Shirt",
      category: "T-Shirts",
      image: "/images/product-6.jpg",
      price: 160,
      brand: "Crocodile",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Formal Shirt",
      category: "Shirts",
      image: "/images/product-5.jpg",
      price: 110,
      brand: "Lou-Phillipe",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};

export default data;
